-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 15:45:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema studyplacedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema studyplacedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `studyplacedb` DEFAULT CHARACTER SET utf8 ;
USE `studyplacedb` ;

-- -----------------------------------------------------
-- Table `studyplacedb`.`AnswersForQuestions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`AnswersForQuestions` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`AnswersForQuestions` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QuestionID` INT NOT NULL,
  `Value` VARCHAR(45) NOT NULL,
  `IsCorrect` TINYINT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `AnswersForQuestions_Questions`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `studyplacedb`.`Questions` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Certificates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`Certificates` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`Certificates` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `CourseID` INT NOT NULL,
  `Mark` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Course_idx` (`CourseID` ASC) VISIBLE,
  INDEX `User_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `Certificates_Courses`
    FOREIGN KEY (`CourseID`)
    REFERENCES `studyplacedb`.`Courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Certificates_Users`
    FOREIGN KEY (`UserID`)
    REFERENCES `studyplacedb`.`Users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`Comments` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`Comments` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `UserID` INT NOT NULL,
  `Text` LONGTEXT NOT NULL,
  `CourseID` INT NOT NULL,
  `PublicationID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Course_idx` (`CourseID` ASC) VISIBLE,
  INDEX `Publication_idx` (`PublicationID` ASC) VISIBLE,
  INDEX `User_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `Comments_Courses`
    FOREIGN KEY (`CourseID`)
    REFERENCES `studyplacedb`.`Courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Comments_Publications`
    FOREIGN KEY (`PublicationID`)
    REFERENCES `studyplacedb`.`Publications` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Comments_Users`
    FOREIGN KEY (`UserID`)
    REFERENCES `studyplacedb`.`Users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS studyplacedb.Courses ;

CREATE TABLE IF NOT EXISTS studyplacedb.Courses (
  ID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(45) NOT NULL,
  Description LONGTEXT NOT NULL,
  Password VARCHAR(45) NULL,
  TeacherID INT NOT NULL,
  Picture BLOB NULL,
  Price DOUBLE NULL,
  PRIMARY KEY (ID),
  INDEX Teacher_idx (TeacherID ASC) VISIBLE,
  CONSTRAINT Courses_Users
    FOREIGN KEY (TeacherID)
    REFERENCES studyplacedb.Users (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`Files` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`Files` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Value` BLOB NOT NULL,
  `PublicationID` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Publication_idx` (`PublicationID` ASC) VISIBLE,
  CONSTRAINT `Files_Publications`
    FOREIGN KEY (`PublicationID`)
    REFERENCES `studyplacedb`.`Publications` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`Links` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`Links` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Value` LONGTEXT NOT NULL,
  `PublicationID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Publication_idx` (`PublicationID` ASC) VISIBLE,
  CONSTRAINT `Links_Publications`
    FOREIGN KEY (`PublicationID`)
    REFERENCES `studyplacedb`.`Publications` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Publications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`Publications` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`Publications` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NULL,
  `CourseID` INT NOT NULL,
  `Position` INT NOT NULL,
  `DateTime` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Course_idx` (`CourseID` ASC) VISIBLE,
  CONSTRAINT `Publications_Courses`
    FOREIGN KEY (`CourseID`)
    REFERENCES `studyplacedb`.`Courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`Questions` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`Questions` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TaskID` INT NOT NULL,
  `Question` LONGTEXT NOT NULL,
  `Description` LONGTEXT NULL,
  `Mark` INT NOT NULL,
  `Position` INT NOT NULL,
  `OneCorrectAnswer` TINYINT NOT NULL,
  `File` TINYINT NOT NULL,
  `FreeText` TINYINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Task_idx` (`TaskID` ASC) VISIBLE,
  CONSTRAINT `Questions_Tasks`
    FOREIGN KEY (`TaskID`)
    REFERENCES `studyplacedb`.`Tasks` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`Roles` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`Roles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Role` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`Subscriptions` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`Subscriptions` (
  `UserID` INT NOT NULL,
  `CourseID` INT NOT NULL,
  INDEX `Course_idx` (`CourseID` ASC) VISIBLE,
  INDEX `User_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `Subscriptions_Courses`
    FOREIGN KEY (`CourseID`)
    REFERENCES `studyplacedb`.`Courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Subscriptions_Users`
    FOREIGN KEY (`UserID`)
    REFERENCES `studyplacedb`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`Tasks` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`Tasks` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NULL,
  `CourseID` INT NOT NULL,
  `Position` INT NOT NULL,
  `Test` INT NOT NULL,
  `Deadline` DATETIME NOT NULL,
  `DateTime` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Course_idx` (`CourseID` ASC) VISIBLE,
  CONSTRAINT `Tasks_Courses`
    FOREIGN KEY (`CourseID`)
    REFERENCES `studyplacedb`.`Courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`Users` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`Users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sername` VARCHAR(45) NOT NULL,
  `InfoID` INT NULL,
  `RoleID` INT NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Info_idx` (`InfoID` ASC) VISIBLE,
  INDEX `Role_idx` (`RoleID` ASC) VISIBLE,
  CONSTRAINT `Users_Users_info`
    FOREIGN KEY (`InfoID`)
    REFERENCES `studyplacedb`.`Users_info` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Users_Roles`
    FOREIGN KEY (`RoleID`)
    REFERENCES `studyplacedb`.`Roles` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`UsersAnswers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`UsersAnswers` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`UsersAnswers` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `AnswerForQuestionID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `User_idx` (`UserID` ASC) VISIBLE,
  INDEX `AnswerForQuestion_idx` (`AnswerForQuestionID` ASC) VISIBLE,
  CONSTRAINT `UsersAnswers_AnswerForQuestions`
    FOREIGN KEY (`AnswerForQuestionID`)
    REFERENCES `studyplacedb`.`AnswersForQuestions` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `UsersAnswers_Users`
    FOREIGN KEY (`UserID`)
    REFERENCES `studyplacedb`.`Users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`UsersFTAnswers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`UsersFTAnswers` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`UsersFTAnswers` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `QuestionID` INT NOT NULL,
  `File` BLOB NULL,
  `FreeText` LONGTEXT NULL,
  PRIMARY KEY (`ID`),
  INDEX `User_idx` (`UserID` ASC) VISIBLE,
  INDEX `Question_idx` (`QuestionID` ASC) VISIBLE,
  CONSTRAINT `UsersFTAnswers_Questions`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `studyplacedb`.`Questions` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `UsersFTAnswers_Users`
    FOREIGN KEY (`UserID`)
    REFERENCES `studyplacedb`.`Users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `studyplacedb`.`Users_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`Users_info` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`Users_info` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Picture` BLOB NULL,
  `IsLocked` TINYINT NULL,
  `Web-site` VARCHAR(45) NULL,
  `Messanger` VARCHAR(45) NULL,
  `E-Mail` VARCHAR(45) NULL,
  `About` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

INSERT INTO Roles VALUES(DEFAULT, 'admin');
INSERT INTO Roles VALUES(DEFAULT, 'user');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
