-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 18:00:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema studyplacedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `studyplacedb` ;

-- -----------------------------------------------------
-- Schema studyplacedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `studyplacedb` DEFAULT CHARACTER SET utf8 ;
USE `studyplacedb` ;

-- -----------------------------------------------------
-- Table `studyplacedb`.`answersforquestions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`answersforquestions` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`answersforquestions` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `QuestionID` INT NOT NULL,
  `Value` VARCHAR(45) NOT NULL,
  `IsCorrect` TINYINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `AnswersForQuestions_Questions` (`QuestionID` ASC) VISIBLE,
  CONSTRAINT `AnswersForQuestions_Questions`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `studyplacedb`.`questions` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`certificates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`certificates` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`certificates` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `CourseID` INT NOT NULL,
  `Mark` DOUBLE NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Course_idx` (`CourseID` ASC) VISIBLE,
  INDEX `User_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `Certificates_Courses`
    FOREIGN KEY (`CourseID`)
    REFERENCES `studyplacedb`.`courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Certificates_Users`
    FOREIGN KEY (`UserID`)
    REFERENCES `studyplacedb`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`comments` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`comments` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DateTime` DATETIME NOT NULL,
  `UserID` INT NOT NULL,
  `Text` LONGTEXT NOT NULL,
  `CourseID` INT NULL,
  `PublicationID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Course_idx` (`CourseID` ASC) VISIBLE,
  INDEX `Publication_idx` (`PublicationID` ASC) VISIBLE,
  INDEX `User_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `Comments_Courses`
    FOREIGN KEY (`CourseID`)
    REFERENCES `studyplacedb`.`courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Comments_Publications`
    FOREIGN KEY (`PublicationID`)
    REFERENCES `studyplacedb`.`publications` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Comments_Users`
    FOREIGN KEY (`UserID`)
    REFERENCES `studyplacedb`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`courses` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`courses` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NOT NULL,
  `Password` VARCHAR(45) NULL DEFAULT NULL,
  `TeacherID` INT NOT NULL,
  `Picture` LONGTEXT NULL DEFAULT NULL,
  `Price` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Teacher_idx` (`TeacherID` ASC) VISIBLE,
  CONSTRAINT `Courses_Users`
    FOREIGN KEY (`TeacherID`)
    REFERENCES `studyplacedb`.`users` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`files` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`files` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Value` LONGTEXT NOT NULL,
  `PublicationID` INT NOT NULL,
  `Type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Publication_idx` (`PublicationID` ASC) VISIBLE,
  CONSTRAINT `Files_Publications`
    FOREIGN KEY (`PublicationID`)
    REFERENCES `studyplacedb`.`publications` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`links`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`links` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`links` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Value` LONGTEXT NOT NULL,
  `PublicationID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Publication_idx` (`PublicationID` ASC) VISIBLE,
  CONSTRAINT `Links_Publications`
    FOREIGN KEY (`PublicationID`)
    REFERENCES `studyplacedb`.`publications` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`publications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`publications` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`publications` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NULL DEFAULT NULL,
  `CourseID` INT NOT NULL,
  `Position` INT NOT NULL,
  `DateTime` DATETIME NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Course_idx` (`CourseID` ASC) VISIBLE,
  CONSTRAINT `Publications_Courses`
    FOREIGN KEY (`CourseID`)
    REFERENCES `studyplacedb`.`courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`questions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`questions` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`questions` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TaskID` INT NOT NULL,
  `Question` LONGTEXT NOT NULL,
  `Description` LONGTEXT NULL DEFAULT NULL,
  `Mark` INT NOT NULL,
  `Position` INT NOT NULL,
  `OneCorrectAnswer` TINYINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Task_idx` (`TaskID` ASC) VISIBLE,
  CONSTRAINT `Questions_Tasks`
    FOREIGN KEY (`TaskID`)
    REFERENCES `studyplacedb`.`tasks` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`roles` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`roles` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Role` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`subscriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`subscriptions` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`subscriptions` (
  `UserID` INT NOT NULL,
  `CourseID` INT NOT NULL,
  INDEX `Course_idx` (`CourseID` ASC) VISIBLE,
  INDEX `User_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `Subscriptions_Courses`
    FOREIGN KEY (`CourseID`)
    REFERENCES `studyplacedb`.`courses` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Subscriptions_Users`
    FOREIGN KEY (`UserID`)
    REFERENCES `studyplacedb`.`users` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`tasks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`tasks` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`tasks` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` LONGTEXT NULL DEFAULT NULL,
  `publications_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_tasks_publications1_idx` (`publications_ID` ASC) VISIBLE,
  CONSTRAINT `fk_tasks_publications1`
    FOREIGN KEY (`publications_ID`)
    REFERENCES `studyplacedb`.`publications` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`users` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sername` VARCHAR(45) NOT NULL,
  `InfoID` INT NULL DEFAULT NULL,
  `RoleID` INT NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `Info_idx` (`InfoID` ASC) VISIBLE,
  INDEX `Role_idx` (`RoleID` ASC) VISIBLE,
  CONSTRAINT `Users_Roles`
    FOREIGN KEY (`RoleID`)
    REFERENCES `studyplacedb`.`roles` (`ID`),
  CONSTRAINT `Users_Users_info`
    FOREIGN KEY (`InfoID`)
    REFERENCES `studyplacedb`.`users_info` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`users_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`users_info` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`users_info` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Picture` LONGTEXT NULL DEFAULT NULL,
  `IsLocked` TINYINT NULL DEFAULT NULL,
  `Web-site` VARCHAR(45) NULL DEFAULT NULL,
  `Messanger` VARCHAR(45) NULL DEFAULT NULL,
  `E-Mail` VARCHAR(45) NULL DEFAULT NULL,
  `About` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`usersanswers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`usersanswers` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`usersanswers` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `AnswerForQuestionID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `User_idx` (`UserID` ASC) VISIBLE,
  INDEX `AnswerForQuestion_idx` (`AnswerForQuestionID` ASC) VISIBLE,
  CONSTRAINT `UsersAnswers_AnswerForQuestions`
    FOREIGN KEY (`AnswerForQuestionID`)
    REFERENCES `studyplacedb`.`answersforquestions` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `UsersAnswers_Users`
    FOREIGN KEY (`UserID`)
    REFERENCES `studyplacedb`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `studyplacedb`.`usersftanswers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `studyplacedb`.`usersftanswers` ;

CREATE TABLE IF NOT EXISTS `studyplacedb`.`usersftanswers` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `QuestionID` INT NOT NULL,
  `File` BLOB NULL DEFAULT NULL,
  `FreeText` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  INDEX `User_idx` (`UserID` ASC) VISIBLE,
  INDEX `Question_idx` (`QuestionID` ASC) VISIBLE,
  CONSTRAINT `UsersFTAnswers_Questions`
    FOREIGN KEY (`QuestionID`)
    REFERENCES `studyplacedb`.`questions` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `UsersFTAnswers_Users`
    FOREIGN KEY (`UserID`)
    REFERENCES `studyplacedb`.`users` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
